#!/bin/bash -e

MBD_HOME=~mini-buildd

# Use first found mirror from sources as default
_read_mirror()
{
	for s in /etc/apt/sources.list $(ls /etc/apt/sources.list.d/*.list 2>/dev/null | sort); do
		[ -z "${MIRROR}" ] || break
		MIRROR=$(grep -1 "^deb " "${s}" 2>/dev/null |head -n1 | cut -d" " -f2)
	done
	read -p "Mirror: " -e -i "${MIRROR}" MIRROR
}

_head()
{
	printf "\n=> ${*}\n"
}


mbd_purge()
{
	_head "Purging ${MBD_HOME}"
	sudo dpkg --purge mini-buildd
}

mbd_build_install()
{
	_head "Building && installing snapshot..."
	git dch --snapshot --auto
	git-buildpackage --git-ignore-new -us -uc
	cat <<EOF | sudo debconf-set-selections -
mini-buildd mini-buildd/admin_password password admin
EOF
	sudo debi
}

mbd_build_install_default()
{
	mbd_purge
	mbd_build_install

	_head "Creating default config..."
	_read_mirror
	sudo su - mini-buildd -c "mini-buildd --foreground --verbose --verbose --debug --create-default-config=${MIRROR}"
}

for c in $(compgen -A function | grep '^mbd_'); do
	ACTIONS+="${c:4}|"
done
trap "printf '\nUsage: ${0} ${ACTIONS}\n' >&2" ERR

if [ -n "${1}" ]; then
	mbd_${1}
	shift
fi
