#!/bin/bash -e

MBD_HOME=~mini-buildd

# Use first found mirror from sources as default
_read_mirror()
{
	for s in /etc/apt/sources.list $(ls /etc/apt/sources.list.d/*.list 2>/dev/null | sort); do
		[ -z "${MIRROR}" ] || break
		MIRROR=$(grep "^deb " "${s}" 2>/dev/null | head -n1 | cut -d" " -f2)
	done
	read -p "Mirror: " -e -i "${MIRROR}" MIRROR
}

_head()
{
	printf "\n=> ${*}\n"
}

PYPATH="$(readlink -f $(dirname $0))"
DJSETTINGS="doc.django_settings"

pyenv()
{
	export PYTHONPATH="${PYPATH}"
	export DJANGO_SETTINGS_MODULE="${DJSETTINGS}"
}

mbd_pep8()
{
	(
		set +e
		pyenv
		# squeeze version does not set an error exit status
		t=$(mktemp)
		trap "rm ${t}" EXIT
		pep8 --ignore=E501,E122 mini-buildd mini_buildd/ | tee "${t}"
		[ ! -s "${t}" ]
	)
}

mbd_pydoctests()
{
	(
		pyenv
		python -m doctest -v mini_buildd/misc.py
		python -m doctest -v mini_buildd/gnupg.py
	)
}

mbd_pyflakes()
{
	(
		pyenv
		pyflakes mini-buildd mini_buildd/
	)
}

mbd_pylintgeneratedmembers()
{
	# Generate all identifiers with "has no xxx member"
	# error. These are most likely false-positive due to django
	# models.
	for o in $(${0} pylint | grep "has no.*member" | cut -d"'" -f4 | sort | uniq); do
		printf "${o},"
	done
	printf "\n"
}

mbd_pylint()
{
	if [ "$(lsb_release -s -c)" = "squeeze" ]; then
		printf "W: pylint/squeeze can't be set up to work for us (skipping)" >&2
	else
		(
			pyenv
			pylint --rcfile="$(pwd)/.pylintrc" --reports=no setup.py mini-buildd mini_buildd/
		)
	fi
}

mbd_pychecker()
{
	(
		pyenv
		pychecker mini-buildd $(find mini_buildd/ -name "*.py")
	)
}

mbd_pydjangolint()
{
	(
		pyenv
		django-lint --reports mini_buildd/
	)
}

mbd_pychecks()
{
	local tests="pep8 pydoctests pyflakes pylint"
	for t in ${tests}; do
		echo "=> mbd_${t}"
		mbd_${t}
	done
	printf "\nOK. Tests passed: %s\n" "${tests}"
}

mbd_purge()
{
	_head "Purging ${MBD_HOME}"
	sudo dpkg --purge mini-buildd

	# @todo: Workaround only as long as mini-buildd doesn't yet do it
	sudo rm -v -f /etc/schroot/chroot.d/mini-buildd-*

	# Also test mini-buildd's internal sbuild key workaround
	sudo rm -v -f /var/lib/sbuild/apt-keys/*
}

mbd_build()
{
	mbd_pychecks
	_head "Building snapshot..."
	git dch --snapshot --auto --ignore-branch
	git-buildpackage --git-ignore-new --git-ignore-branch -us -uc
}

mbd_install()
{
	_head "Installing snapshot..."
	cat <<EOF | sudo debconf-set-selections --verbose -
mini-buildd mini-buildd/admin_password password admin
#mini-buildd mini-buildd/options string --verbose --verbose --debug
mini-buildd mini-buildd/options string --verbose --debug=main,django,repository
EOF
	sudo debi
}

mbd_default()
{
	# copy to avoid perm problems
	cp ./mini_buildd/fixtures/${1}.json /tmp/fix.json
	sudo su - mini-buildd -c "mini-buildd --loaddata=/tmp/fix.json"
}

mbd_test()
{
	read -p "About to upload test packages. All configured? [ http://$(hostname -f):8066 ]" dummy
	(
		cd ./examples
		./packages.testbuild ${1}
	)
}

mbd_all()
{
	mbd_build
	mbd_purge
	mbd_install
	mbd_test
}

sep=" "
for c in $(compgen -A function | grep '^mbd_'); do
	ACTIONS+="${sep}${c:4}"
	sep="|"
done
trap "printf '\nUsage: ${0}${ACTIONS}[_arg1_arg2..] \n' >&2" ERR

[ "${*}" ]

for ACTION in ${*}; do
	func=$(echo "${ACTION}" | cut -d_ -f1)
	args=""
	if echo "${ACTION}" | grep -q "_"; then
		args=$(echo "${ACTION}" | cut -d_ -f2- | tr "_" " ")
	fi
	mbd_${func} ${args}
done
