#!/bin/sh -e

. `dirname $0`/mbd-common.sh

mbd_opt_init "Mini-buildd: Remove package(s) from the repository.

Examples:
 mbd-remove-pkg -p \"*_*\": Remove ALL packages.
 mbd-remove-pkg -p \"etch*/*_*\": Remove ALL packages from all etch distributions.
 mbd-remove-pkg -p \"package_*\": Remove all versions of package.
 mbd-remove-pkg -p \"package_1.2.3-1\": Remove versions 1.2.3-1 of package."
mbd_opt_add "p:" "Package pattern (see find); for example PACKAGE_VERSION."
mbd_opt_add "R" "Actually do removal."
mbd_opt_parse "$@"

echo "WARNING: This is EXPERIMENTAL. Use only for testing." >&2
echo "WARNING: This depends on changes files present in repo for any upload -- not true for all versions if mini-dinstall." >&2
echo >&2

PACKAGE=`mbd_opt_get p`
REMOVEDIR="${MBD_HOME}/REMOVED/`date --utc +%Y%m%d:%H%M%S:%N`"

mbd_remove_file()
{
	local f="${1}"
	local cmd="mv ${1} ${REMOVEDIR}/"

	if mbd_opt_given R; then
		mkdir -p "${REMOVEDIR}"
		echo "Run (NOT IMPL): ${cmd}"
	else
		echo "Would run: ${cmd}"
	fi
}

/etc/init.d/mini-buildd-rep stop

# Iterate over all changes files
for c in `find ${MBD_HOME}/rep/ -type f -name "${PACKAGE}.changes"`; do
	dir=`dirname ${c}`
	mbdParseCF "${c}"
	log="${MBD_HOME}/log/`echo "${mbdParseCF_package}" | cut -d_ -f1`/${mbdParseCF_version}"

	echo "Changes: ${c}"

	for f in ${mbdParseCF_files}; do
		mbd_remove_file "${dir}/${f}"
	done
	mbd_remove_file "${dir}.db"
	mbd_remove_file "${log}"
	mbd_remove_file "${log}"
done

/etc/init.d/mini-buildd-rep restart
