#!/bin/sh -e

. `dirname $0`/mbd-common.sh
. "${MBD_BLDCONFIGFILE}"

# Update config file; this must be first
if [ ! -e "/etc/init.d/mini-buildd-rep" ]; then
	# -bld w/o -rep only; retrieve config from rephost.
	mbdGetUrl "${MBD_REPCONFIGFILE}" "http://${mbd_rephttphost}/~mini-buildd/config" || true
fi

mbd_opt_init "Mini-buildd: Builder update script."
mbd_opt_parse "$@"
mbdCheckUser mini-buildd

cd "${MBD_HOME}"
. "${MBD_REPCONFIGFILE}"

mkdir -p "bld/builds"
mkdir -p "bld/chroots"

cat <<EOF >"${MBD_SBUILDCONFIGFILE}"
# Mode "user": Use retval to check if build was successful.
\$sbuild_mode = "user";
# We don't use sbuild-generated log files
\$nolog = 1;
# We always want to update the cache as we generate sources.list on thy fly.
\$apt_update = 1;
# APT-Policy to "1", so we can satisfy dependencies via all sources we added.
\$apt_policy = 1;

# Add path for ccache
\$path = "/usr/lib/ccache:/usr/sbin:/usr/bin:/sbin:/bin:/usr/X11R6/bin:/usr/games";

# Builder identity
\$mailfrom = "${MBD_AUTOBUILD_MAINTAINER} on `hostname -f` <${mbd_mail}>";
\$mailto = "${mbd_mail}";
\$maintainer_name='${MBD_AUTOBUILD_MAINTAINER}';

# don't remove this, Perl needs it:
1;
EOF
${MBD_LOG} -s "${MBD_SBUILDCONFIGFILE} updated."

${MBD_LIB}/mbd-update-common

# Make some items accessible via http
${MBD_LOG} -s "`ln -s -f -v ../bld public_html/ 2>&1`"

mbdUpdateSshKeyring "${mbd_rephost}"

# Check/prepare chroots for all dists.
for dist in `echo "${mbd_dists}" | tr -d ","`; do
	for arch in `echo "${mbd_archs}" | tr -d ","`; do
		# Are we responsible for that arch?
		MBD_TMP_BLDHOST="mbd_bldhost_${arch}"
		if [ "${mbd_bldhost}" = "${!MBD_TMP_BLDHOST}" ]; then
			MBD_TMP_CHROOT="mbd-${dist}-${mbd_id}-${arch}"

			${MBD_LOG} -s "Updating chroot ${MBD_TMP_CHROOT}..."
			if cat <<EOF | schroot -c "${MBD_TMP_CHROOT}-source" -u root 2>&1 | ${MBD_LOG} -s; then
set -e
export DEBIAN_FRONTEND="noninteractive"
apt-get update
apt-get --yes --ignore-missing dist-upgrade
[ -z "${MBD_CHROOT_EXTRA_PACKAGES}" ] || apt-get --yes install ${MBD_CHROOT_EXTRA_PACKAGES}
apt-get clean

# Workaround for Debian Bug #327477 (bash building)
[ -e /dev/fd ] || ln -sv /proc/self/fd /dev/fd
[ -e /dev/stdin ] || ln -sv fd/0 /dev/stdin
[ -e /dev/stdout ] || ln -sv fd/1 /dev/stdout
[ -e /dev/stderr ] || ln -sv fd/2 /dev/stderr
EOF
				${MBD_LOG} -s "Chroot ${MBD_TMP_CHROOT} successfully updated."
			else
				${MBD_LOG} -s "*ERROR* updating chroot ${MBD_TMP_CHROOT}."
			fi
		fi
	done
done

exit 0
