#!/bin/sh -e

. `dirname $0`/mbd-common.sh
. "${MBD_REPCONFIGFILE}"
. "${MBD_BLDCONFIGFILE}"

mbd_opt_init "Mini-buildd: Show and optionally delete cruft from earlier versions."
mbd_opt_add "u" "Update cruft -- i.e., actually perform action shown per file w/o -u."
mbd_opt_parse "$@"

cd "${MBD_HOME}"

MBD_TMP_OBSOLETE="*.sources.list *.update.log setup-lvm.log lvm_pv0.img gpg_key_template repository_signing_key.asc *.ssh_key.asc \
                  bld/*.log bld/current* bld/*.dsc bld/*.diff.gz bld/*.tar.gz bld/*.deb bld/*.udeb bld/*.changes bld/*.changes.lintian bld/*.upload bld/logs \
                  rep/dput.cf rep/mini-dinstall/REJECT `find bld/chroots/ -mindepth 1 ! -name 'lvm.device' -a ! -name 'lvm.image'`"

for f in ${MBD_TMP_OBSOLETE}; do
	if [ -e "${f}" ]; then
		if mbd_opt_given u; then
			${MBD_LOG} -s "Cruft removed: `rm -rfv "${f}"`"
		else
			${MBD_LOG} -s "Cruft (-u would remove): ${f}"
		fi
	fi
done
