#!/bin/bash -e

. $(dirname $0)/mbd-common.sh
mbd_opt_init "Mini-buildd: Repository html update script."
mbd_opt_parse "$@"
mbdCheckUser mini-buildd

cd "${MBD_HOME}"
. "${MBD_REPCONFIGFILE}"

# Rudimentary HTML index
mbdBldHtml()
{
	mbdParseArch "${1}"

	local urlbase="http://${mbdParseArch_host}:${mbd_httpport}/~mini-buildd"
cat <<EOF
<a href="${urlbase}/bld">Buildhost ${mbdParseArch_host}</a>:
<a href="${urlbase}/pgp_key.asc">PGP Key</a>,
<a href="${urlbase}/ssh_key.asc">SSH Key</a>
EOF
}

MBD_TMP_DISTS=$(mbdD2SList "${mbd_dists}")
MBD_TMP_ARCHS=$(mbdD2SList "${mbd_archs}")
MBD_TMP_TITLE="Mini-Buildd network for \"${mbd_id}\""
cat <<EOF >"${MBD_HTML_INDEXFILE}"
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<html>
<head>
<meta http-equiv="Content-Style-Type" content="text/css">
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" >

<title>${MBD_TMP_TITLE}</title>

<style type="text/css">
  h1 {border-width: 1; border: solid; text-align: center}
  h2 {border-width: 1; text-align: center}
  h3 {border-width: 1; text-align: center}
  h4 {border-width: 0; text-align: left}
  pre {background-color:lightgrey;}
</style>

<body>

<div>
<input type="checkbox" id="details" onclick="show_details()">
Show details
<small>(mini-buildd $(dpkg -s mini-buildd-rep | grep ^Version | cut -d: -f2-))
</small>
</div>

<script type="text/javascript">

<!--
function show_details()
{
  var details = (document.getElementById('details').checked == true);

  var divTags = document.getElementsByTagName('div');
  for (var i=0; i < divTags.length; i++)
  {
    if (divTags[i].getAttribute("class") == "details")
    {
      if (details)
      {
        divTags[i].style.display = '';
      }
      else
      {
        divTags[i].style.display = 'none';
      }
    }
  }
}
//-->
show_details();
</script>

<h1>${MBD_TMP_TITLE}</h1>

<div>

</div>

$(for d in ${MBD_TMP_DISTS}; do
   echo "<div style='background-color: lightblue; '>"

   echo "<h2>Base distribution ${d}</h2>"

   echo "<h3>Uploadable distributions</h3>"
   for e in "experimental" "unstable"; do
     DIST="${d}-${mbd_id}-${e}"
     KIND="mbd_${e}"

     echo "<h4><a href=\"rep/dists/${DIST}\">${DIST}</a>: ${d} ${e} packages for ${mbd_id}</h4>"

     echo "<small><em>Mandatory version part: </em></small><pre style='display:inline'>"
     mbdGetMandatoryVersionPart "${DIST}"
     echo "</pre>"
     echo "<small><em>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Apt source line: </em></small><pre style='display:inline'>"
     AUTH_VERBOSITY='quiet' mbdGenSources ${d} "${KIND}" "" "noheader"
     echo "</pre>"
     echo "<div class='details' style='display:none;'>"
     for a in ${MBD_TMP_ARCHS}; do
       MBD_TMP_BO="mbd_deb_build_options_${a}"

       echo -n "<h4>${a} builder ("
       mbdBldHtml "${a}"
       echo ", BUILD_OPTIONS=\"${!MBD_TMP_BO}\"):</h4>"

       echo "Sources:<pre>"
       AUTH_VERBOSITY='quiet' mbdGenSources "${d}" "base extra" "${a}"
       echo "</pre>"
       echo "Preferences:<pre>"
       AUTH_VERBOSITY='quiet' mbdGenPreferences "${d}" "base extra" "${a}"
       echo "</pre>"
     done
     echo "<hr/>"
     echo "</div>"
   done
   echo "<hr/>"
   echo "<h3>Staged distributions</h3>"
   for e in "testing" "stable"; do
     DIST="${d}-${mbd_id}-${e}"
     KIND="mbd_${e}"

     echo "<h4><a href=\"rep/dists/${DIST}\">${DIST}</a>: ${d} ${e} packages for ${mbd_id}</h4>"

     echo "<small><em>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Apt source line: </em></small><pre style='display:inline'>"
     AUTH_VERBOSITY='quiet' mbdGenSources ${d} "${KIND}" "" "noheader"
     echo "</pre>"
   done

   echo "</div>"
 done)

<script  type="text/javascript">
show_details();
</script>

</html>
EOF
${MBD_LOG} -s "I: ${MBD_HTML_INDEXFILE} updated."

exit 0
