#!/bin/bash -e

. $(dirname $0)/mbd-common.sh
mbd_opt_init "Mini-buildd: Repository update script."
mbd_opt_add "p" "Special handling for debian postinstall run."
mbd_opt_parse "$@"
mbdCheckUser mini-buildd

cd "${MBD_HOME}"
. "${MBD_REPCONFIGFILE}"

${MBD_LIB}/mbd-update-common

# Run mbd-update-bld on all build hosts
for host in $(mbdGetBldHosts); do
	mbdUpdateSshKeyring "${host}"
	${MBD_LOG} -s "I: Updating build host ${host}..."
	if ! ssh -o StrictHostKeyChecking="no" -p "${mbd_sshport}" "${host}" "${MBD_LIB}/mbd-update-bld"; then
		${MBD_LOG} -s "E: Updating build host ${host} FAILED (ignore if not set up yet)"
	fi
done

if ! mbd_opt_given p; then
	${MBD_LOG} -s "I: $(/etc/init.d/mini-buildd-rep restart 2>&1)"
fi

exit 0
