#!/bin/bash -e

. $(dirname $0)/mbd-common.sh
mbd_opt_init "Mini-buildd: Repository update script."
mbd_opt_add "p" "Special handling for debian postinstall run."
mbd_opt_parse "$@"
mbdCheckUser mini-buildd

cd "${MBD_HOME}"
. "${MBD_REPCONFIGFILE}"

MBD_TMP_DISTS=$(mbdD2SList "${mbd_dists}")

cat <<EOF >"${MBD_REPREPRO_DISTSFILE}"
$(for d in ${MBD_TMP_DISTS}; do
   echo "Codename: ${d}-${mbd_id}-experimental";
   echo "Suite: ${d}-${mbd_id}-experimental";
   echo "Label: ${d}-${mbd_id}-experimental";
   echo "Origin: mini-buildd-${mbd_id}";
   echo "Components: main contrib non-free";
   echo "Architectures: source $(mbdD2SList "${mbd_archs}")";
   echo "Description: EXPERIMENTAL ${d} packages for ${mbd_id}.";
   echo "SignWith: default";
   echo "NotAutomatic: yes";
   echo;
   echo "Codename: ${d}-${mbd_id}-unstable";
   echo "Suite: ${d}-${mbd_id}-unstable";
   echo "Label: ${d}-${mbd_id}-unstable";
   echo "Origin: mini-buildd-${mbd_id}";
   echo "Components: main contrib non-free";
   echo "Architectures: source $(mbdD2SList "${mbd_archs}")";
   echo "Description: Unstable ${d} packages for ${mbd_id}.";
   echo "SignWith: default";
   echo "NotAutomatic: yes";
   echo "ButAutomaticUpgrades: yes";
   echo;
   echo "Codename: ${d}-${mbd_id}-testing";
   echo "Suite: ${d}-${mbd_id}-testing";
   echo "Label: ${d}-${mbd_id}-testing";
   echo "Origin: mini-buildd-${mbd_id}";
   echo "Components: main contrib non-free";
   echo "Architectures: source $(mbdD2SList "${mbd_archs}")";
   echo "Description: Testing ${d} packages for ${mbd_id}.";
   echo "SignWith: default";
   echo "NotAutomatic: yes";
   echo "ButAutomaticUpgrades: yes";
   echo;
   echo "Codename: ${d}-${mbd_id}-stable";
   echo "Suite: ${d}-${mbd_id}-stable";
   echo "Label: ${d}-${mbd_id}-stable";
   echo "Origin: mini-buildd-${mbd_id}";
   echo "Components: main contrib non-free";
   echo "Architectures: source $(mbdD2SList "${mbd_archs}")";
   echo "Description: Stable ${d} packages for ${mbd_id}.";
   echo "SignWith: default";
   echo "NotAutomatic: yes";
   echo "ButAutomaticUpgrades: yes";
   echo;
 done)
EOF
${MBD_LOG} -s "I: ${MBD_REPREPRO_DISTSFILE} updated."

cat <<EOF >"${MBD_REPREPRO_INCOMINGFILE}"
Name: INCOMING
TempDir: /tmp
IncomingDir: ${MBD_INCOMING}
Allow: $(for d in ${MBD_TMP_DISTS}; do echo -n "${d}-${mbd_id}-unstable ${d}-${mbd_id}-experimental "; done)
EOF
${MBD_LOG} -s "I: ${MBD_REPREPRO_INCOMINGFILE} updated."

${MBD_LIB}/mbd-update-common
${MBD_LIB}/mbd-update-rep-html

# Update repo-host key for 05_apt-secure
cp "public_html/pgp_key.asc" ".mini-buildd/apt-secure.d/auto-mini-buildd.key"

# Update all indices (or create on initial install) via reprepro
(cd rep && reprepro clearvanished && reprepro export)

# Run mbd-update-bld on all build hosts
for host in $(mbdGetBldHosts); do
	mbdUpdateSshKeyring "${host}"
	${MBD_LOG} -s "I: Updating build host ${host}..."
	if ! ssh -o StrictHostKeyChecking="no" -p "${mbd_sshport}" "${host}" "${MBD_LIB}/mbd-update-bld"; then
		${MBD_LOG} -s "E: Updating build host ${host} FAILED (ignore if not set up yet)"
	fi
done

if ! mbd_opt_given p; then
	${MBD_LOG} -s "I: $(/etc/init.d/mini-buildd-rep restart 2>&1)"
fi

exit 0
