#!/bin/bash -e

. $(dirname $0)/mbd-common.sh
mbd_opt_init "Mini-buildd: Common update script."
mbd_opt_parse "$@"
mbdCheckUser mini-buildd

cd "${MBD_HOME}"
. "${MBD_REPCONFIGFILE}"

if ! grep -q "PATH=\"${MBD_LIB}" .profile 2>/dev/null; then
	echo "PATH=\"${MBD_LIB}:\${PATH}\"" >>.profile
	echo "export PATH" >>.profile
	${MBD_LOG} -s "I: .profile patched: Adding ${MBD_LIB} to path."
fi

if [ -e "${MBD_SSHSECKEYFILE}" ]; then
	${MBD_LOG} -s "I: Not touching existing ${MBD_SSHSECKEYFILE}."
else
	ssh-keygen -t "dsa" -f "${MBD_SSHSECKEYFILE}" -N ""
	cat "${MBD_SSHPUBKEYFILE}" >>.ssh/authorized_keys
fi

mkdir -p public_html
gpg --armor --export "mini-buildd@$(hostname -f)" >public_html/pgp_key.asc
cat "${MBD_SSHPUBKEYFILE}" >public_html/ssh_key.asc

exit 0
