#!/bin/sh -e

# Manage sources.lists on "setup-start", for user "mini-buildd".

log_info()
{
	if [ "${AUTH_VERBOSITY}" != "quiet" ]; then
		echo "I: [mini-buildd]: ${1}" >&2
	fi
}

# Generates sources.list to stdout
gen_sources_list()
{
	# Sources directory
	local sd="${1}"
	# Types: base, mbd, extra
	local types="${2}"
	# Arch: Also search for specialised arch sources list
	local arch="${3}"

	for l in ${types}; do
		for a in any ${arch}; do
			local f="${sd}/${l}.${a}.list"
			if [ -f "${f}" ]; then
				echo "# ${l}-${a}"
				cat "${f}"
				echo ""
				log_info "Sources list added: ${f}."
			fi
		done
	done
}

# We only act on chroots having "mini-buildd" in description
if echo "${CHROOT_DESCRIPTION}" | grep --ignore-case --quiet "mini-buildd"; then
	if [ "${1}" = "setup-start" ]; then
		# CHROOT_DEVICE="/DIR/mbd-etch-ab-i386"
		DIST=`basename "${CHROOT_DEVICE}" | cut -d- -f2-3`
		ARCH=`basename "${CHROOT_DEVICE}" | cut -d- -f4-`

		# Sources list file to generate in chroot
		SOURCES_LIST="${CHROOT_PATH}/etc/apt/sources.list"
		SOURCES_DIR="/home/mini-buildd/bld/chroots/${DIST}"

		# Base is for both, source and snasphots
		gen_sources_list "${SOURCES_DIR}" "base" "${ARCH}" >"${SOURCES_LIST}"

		# Add extra sources for snapshots driven by mini-buildd only
		if [ "${CHROOT_TYPE}" = "lvm-snapshot" -a "${AUTH_USER}" = "mini-buildd" ]; then
			gen_sources_list "${SOURCES_DIR}" "mbd extra" "${ARCH}" >>"${SOURCES_LIST}"
		fi
	fi
fi
