#!/bin/sh -e

# Generate sources.lists on "setup-start" for "mini-buildd" chroots.

if [ "${1}" = "setup-start" ] && echo "${CHROOT_DESCRIPTION}" | grep --ignore-case --quiet "mini-buildd"; then
	# Bootstrap mbd lib and value support
	. /usr/lib/mini-buildd/mbd-common.sh
	. /home/mini-buildd/.mini-buildd.conf

	# CHROOT_DEVICE="/DIR/mbd-etch-ab-i386"
	BASEDIST=`basename "${CHROOT_DEVICE}" | cut -d- -f2`
	ARCH=`basename "${CHROOT_DEVICE}" | cut -d- -f4-`

	# Sources list file to generate in chroot
	SOURCES_LIST="${CHROOT_PATH}/etc/apt/sources.list"

	if [ "${CHROOT_TYPE}" = "lvm-snapshot" -a "${AUTH_USER}" = "mini-buildd" ]; then
		# Snapshot and user mini-buildd: all sources
		mbdGenSources "${BASEDIST}" "base mbd extra" "${ARCH}" >"${SOURCES_LIST}"
	else
		# Other cases (usually likely -source): Only base.
		mbdGenSources "${BASEDIST}" "base" "${ARCH}" >"${SOURCES_LIST}"
	fi
fi
