#!/bin/sh -e

case ${1} in
	purge)
		rm -f /etc/schroot/mini-buildd/fstab
		# On purge, force-remove user mini-buildd along with all files.
		# Be sure to give the user a warning, though, as he might
		# lose valuable data like repositories
		. /usr/share/debconf/confmodule
		db_input critical "mini-buildd/purge_warning" || true
		db_go || true
		userdel --force --remove mini-buildd >/dev/null 2>&1 || true
		;;
esac

#DEBHELPER#

exit 0
