#!/bin/sh -e

case $1 in
	purge)
		if [ -e "/home/mini-buildd/rep" ]; then
			. /usr/share/debconf/confmodule
			db_input critical "mini-buildd-common/purging_repository" || true
			db_go || true
		fi

		# Workaround: deluser does not seem to remove socket files
		find /home/mini-buildd/ -type s -exec rm -f {} \;
		deluser --quiet --remove-home mini-buildd >/dev/null || true
		;;
esac

#DEBHELPER#

exit 0
