#!/bin/sh -e

### BEGIN INIT INFO
# Provides:          mini-buildd-bld
# Required-Start:    $remote_fs
# Required-Stop:
# Default-Start:     S
# Default-Stop:
# Short-Description: Setup loop devices for mini-buildd/lvm if needed
### END INIT INFO

case "$1" in
	start)
		/usr/share/mini-buildd/mbd-setup-lvm -a
		;;
	stop|restart|force-reload)
		echo "Ignored (call with start only)."
		;;
	*)
		echo -e "\nUsage: $0 start" >&2
		exit 1
		;;
esac

exit 0
