# -*- coding: utf-8 -*-
MODELS = [
    "gnupg.AptKey",
    "gnupg.Uploader",
    "gnupg.Remote",
    "source.Archive",
    "source.Architecture",
    "source.Component",
    "source.Source",
    "source.PrioritySource",
    "repository.EmailAddress",
    "repository.Suite",
    "repository.Layout",
    "repository.Distribution",
    "repository.Repository",
    "chroot.Chroot",
    "chroot.FileChroot",
    "chroot.LVMChroot",
    "chroot.LoopLVMChroot",
    "daemon.Daemon"]
